// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { isDemoMode } from '@/demo/mode';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: (input, init) => {
      const method = (init?.method ?? (input instanceof Request ? input.method : 'GET')).toUpperCase();
      if (isDemoMode() && method !== 'GET') {
        return Promise.reject(new Error('Demo mode cannot write to the backend.'));
      }
      return fetch(input, init);
    },
  },
  auth: {
    storage: isDemoMode() ? { getItem: () => null, setItem: () => {}, removeItem: () => {} } : brokeredPreviewStorage(),
    persistSession: !isDemoMode(),
    autoRefreshToken: !isDemoMode(),
    detectSessionInUrl: !isDemoMode(),
  }
});