import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type * as T from './types';
export type {Session,Member,Event,Rsvp,Deal,Question,Thread,Message,Notification,Announcement,AdminStats,Settings} from './types';
export const platformEnabled = import.meta.env.VITE_PLATFORM_BACKEND_ENABLED === 'true';
const url = import.meta.env.VITE_SUPABASE_URL;
const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const client: SupabaseClient | null = platformEnabled && url && key ? createClient(url,key,{auth:{storageKey:'catalyst-platform-auth',persistSession:true,autoRefreshToken:true}}) : null;
export class PlatformError extends Error {
  constructor(public code:'not_enabled'|'unauthenticated'|'forbidden'|'missing_table'|'not_found'|'conflict'|'unknown',message:string){super(message);this.name='PlatformError';}
}
function db(){if(!client)throw new PlatformError('not_enabled','Platform backend is not enabled. Configure Supabase and apply the platform migration first.');return client;}
function fail(e: {code?:string;message?:string}|null){if(!e)return;const code=e.code;throw new PlatformError(code==='PGRST205'||code==='42P01'||code==='PGRST202'?'missing_table':code==='42501'?'forbidden':code==='23505'||code==='P0001'?'conflict':'unknown',e.message||'Backend request failed');}
async function rows(table:string){const result:Record<string,any>[]=[];for(let start=0;;start+=500){const {data,error}=await db().from('platform_'+table).select('*').order(table==='saved_deals'||table==='thread_members'||table==='thread_reads'?'user_id':'id').range(start,start+499);fail(error);result.push(...(data||[]));if(!data||data.length<500)break;}return result;}
async function one(table:string,id:string){const {data,error}=await db().from('platform_'+table).select('*').eq('id',id).maybeSingle();fail(error);if(!data)throw new PlatformError('not_found','Not found or not accessible');return data;}
async function rpc(name:string,args?:Record<string,unknown>){const {data,error}=await db().rpc('platform_'+name,args);fail(error);return data;}
async function write(table:string,value:Record<string,unknown>,id?:string){const q=db().from('platform_'+table);const {data,error}=await (id?q.update(value).eq('id',id):q.insert(value)).select('*').single();fail(error);return data;}
async function remove(table:string,id:string){const {error}=await db().from('platform_'+table).delete().eq('id',id);fail(error);}
const member=(r:Record<string,any>):T.Member=>({id:r.id,email:r.email,name:r.name,role:r.role==='admin'?'admin':'member',city:r.city,bio:r.bio,interests:r.interests||[],notifPrefs:r.notif_prefs||[],createdAt:r.created_at});
const event=(r:Record<string,any>):T.Event=>({id:r.id,title:r.title,startsAt:r.starts_at,endsAt:r.ends_at,venue:r.venue,address:r.address,capacity:r.capacity,coverUrl:r.cover_url,description:r.description,status:r.status,goingCount:Number(r.going_count||0),waitlistCount:Number(r.waitlist_count||0),createdAt:r.created_at});
const deal=(r:Record<string,any>):T.Deal=>({id:r.id,slug:r.slug,name:r.name,line:r.line,sector:r.sector,city:r.city,about:r.about,minCheck:Number(r.min_check||0),valuationCap:r.valuation_cap,instrument:r.instrument,goal:Number(r.goal||0),status:r.status,isSample:r.is_sample,coverUrl:r.cover_url,traction:r.traction||[],useOfFunds:r.use_of_funds||[],createdAt:r.created_at});
const rsvpMap=(r:Record<string,any>):T.Rsvp=>({id:r.id,eventId:r.event_id,userId:r.user_id,memberName:r.member_name||'Member',memberEmail:r.member_email||'',status:r.status,checkedInAt:r.checked_in_at,createdAt:r.created_at});
const question=(r:Record<string,any>):T.Question=>({id:r.id,dealId:r.deal_id,userId:r.user_id,memberName:r.member_name||'Community member',body:r.body,answer:r.answer,answeredAt:r.answered_at,hidden:r.hidden,createdAt:r.created_at});
export async function getSession():Promise<T.Session|null>{const {data:{session},error}=await db().auth.getSession();fail(error);if(!session)return null;const {data,error:profileError}=await db().from('platform_profiles').select('role').eq('id',session.user.id).maybeSingle();fail(profileError);return {userId:session.user.id,email:session.user.email||'',role:data?.role==='admin'?'admin':'member'};}
export function onSession(cb:(session:T.Session|null)=>void){if(!client)return ()=>{};const {data:{subscription}}=client.auth.onAuthStateChange(()=>{setTimeout(()=>{void getSession().then(cb).catch(()=>cb(null));},0);});return ()=>subscription.unsubscribe();}
async function user(){const s=await getSession();if(!s)throw new PlatformError('unauthenticated','Sign in to continue');return s;}
async function admin(){const s=await user();if(s.role!=='admin')throw new PlatformError('forbidden','Admin access required');return s;}
export async function signIn(email:string,password:string){const {error}=await db().auth.signInWithPassword({email,password});fail(error);await rpc('ensure_profile');return getSession();}
export async function signUp(email:string,password:string,name:string){const {data,error}=await db().auth.signUp({email,password,options:{data:{name}}});fail(error);if(data.session)await rpc('ensure_profile');return data.session ? getSession() : null;}
export async function signOut(){const {error}=await db().auth.signOut();fail(error);}
export async function sendReset(email:string){const {error}=await db().auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/forgot-password'});fail(error);}
export async function getMe(){const s=await user();await rpc('ensure_profile');return member(await one('profiles',s.userId));}
export async function updateMe(p:Partial<Pick<T.Member,'name'|'bio'|'city'|'interests'|'notifPrefs'>>){const s=await user();const value:Record<string,unknown>={};if(p.name!==undefined)value.name=p.name;if(p.city!==undefined)value.city=p.city;if(p.bio!==undefined)value.bio=p.bio;if(p.interests!==undefined)value.interests=p.interests;if(p.notifPrefs!==undefined)value.notif_prefs=p.notifPrefs;return member(await write('profiles',value,s.userId));}
async function eventRows(all:boolean,upcoming=false){const q=db().from('platform_events').select('*').order('starts_at');if(!all)q.eq('status','published');if(upcoming)q.gte('starts_at',new Date().toISOString());const {data,error}=await q;fail(error);const counts=await rpc('event_counts')||[];return (data||[]).map(r=>event({...r,...counts.find((c:any)=>c.event_id===r.id)}));}
export async function listEvents(opts:{upcoming?:boolean}={}){return eventRows(false,opts.upcoming);}
export async function getEvent(id:string){const r=await one('events',id);const counts=await rpc('event_counts')||[];return event({...r,...counts.find((c:any)=>c.event_id===id)});}
export async function rsvp(eventId:string){await user();const result=await rpc('rsvp',{p_event_id:eventId,p_cancel:false});return rsvpMap(Array.isArray(result)?result[0]:result);}
export async function cancelRsvp(eventId:string){await user();await rpc('rsvp',{p_event_id:eventId,p_cancel:true});}
export async function myRsvps(){const s=await user();const {data,error}=await db().from('platform_event_rsvps').select('*').eq('user_id',s.userId).order('created_at',{ascending:false});fail(error);return Promise.all((data||[]).map(async r=>({...rsvpMap(r),event:await getEvent(r.event_id)})));}
export async function listDeals(){const {data,error}=await db().from('platform_deals').select('*').eq('status','preview');fail(error);return (data||[]).map(deal);}
export async function getDeal(idOrSlug:string){const all=await listDeals();const d=all.find(d=>d.id===idOrSlug||d.slug===idOrSlug);if(!d)throw new PlatformError('not_found','Listing not found');return d;}
export async function listSaves():Promise<T.Save[]>{const s=await user();const {data,error}=await db().from('platform_saved_deals').select('*').eq('user_id',s.userId);fail(error);return (data||[]).map(r=>({dealId:r.deal_id,createdAt:r.created_at}));}
export async function toggleSave(dealId:string){const s=await user();const {data,error}=await db().from('platform_saved_deals').select('deal_id').eq('user_id',s.userId).eq('deal_id',dealId).maybeSingle();fail(error);if(data){const {error}=await db().from('platform_saved_deals').delete().eq('user_id',s.userId).eq('deal_id',dealId);fail(error);return false;}await write('saved_deals',{user_id:s.userId,deal_id:dealId});return true;}
async function names(ids:string[]){const found:Record<string,string>={};const unique=[...new Set(ids)];for(let i=0;i<unique.length;i+=100){const result=await rpc('member_names',{p_user_ids:unique.slice(i,i+100)})||[];for(const r of result)found[r.id]=r.name;}return found;}
export async function listQuestions(dealId:string){await user();const {data,error}=await db().from('platform_deal_questions').select('*').eq('deal_id',dealId).eq('hidden',false).order('created_at',{ascending:false});fail(error);const labels=await names((data||[]).map(r=>r.user_id));return (data||[]).map(r=>question({...r,member_name:labels[r.user_id]}));}
export async function askQuestion(dealId:string,body:string){const s=await user();return question(await write('deal_questions',{deal_id:dealId,user_id:s.userId,body}));}
export async function listThreads():Promise<T.Thread[]>{await user();const [ts,ms,reads,messages]=await Promise.all([rows('threads'),rows('thread_members'),rows('thread_reads'),rows('messages')]);return ts.map(t=>{const latest=messages.filter(m=>m.thread_id===t.id).sort((a,b)=>b.created_at.localeCompare(a.created_at))[0];const read=reads.find(r=>r.thread_id===t.id);return {id:t.id,kind:t.kind,title:t.title,lastMessageAt:latest?.created_at||t.created_at,unread:!!latest&&(!read||read.read_at<latest.created_at),memberIds:ms.filter(m=>m.thread_id===t.id).map(m=>m.user_id)};});}
export async function listMessages(threadId:string):Promise<T.Message[]>{await user();const {data,error}=await db().from('platform_messages').select('*').eq('thread_id',threadId).order('created_at');fail(error);const labels=await names((data||[]).map(r=>r.user_id));return (data||[]).map(r=>({id:r.id,threadId:r.thread_id,userId:r.user_id,senderName:labels[r.user_id]||'Member',body:r.body,createdAt:r.created_at}));}
export async function sendMessage(threadId:string,body:string){const s=await user();const r=await write('messages',{thread_id:threadId,user_id:s.userId,body});return {id:r.id,threadId:r.thread_id,userId:r.user_id,senderName:'You',body:r.body,createdAt:r.created_at};}
export async function markThreadRead(threadId:string){const s=await user();const {error}=await db().from('platform_thread_reads').upsert({thread_id:threadId,user_id:s.userId,read_at:new Date().toISOString()},{onConflict:'thread_id,user_id'});fail(error);}
export async function listNotifications():Promise<T.Notification[]>{await user();return (await rows('notifications')).sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(r=>({id:r.id,kind:r.kind,title:r.title,body:r.body,link:r.link,readAt:r.read_at,createdAt:r.created_at}));}
export async function markNotificationRead(id:string){const s=await user();const q=db().from('platform_notifications').update({read_at:new Date().toISOString()}).eq('user_id',s.userId);if(id!=='all')q.eq('id',id);const {error}=await q;fail(error);}
export async function adminListEvents(){await admin();return eventRows(true);}
function eventValue(p:Partial<T.EventInput>){const v:Record<string,unknown>={};const pairs={title:'title',startsAt:'starts_at',endsAt:'ends_at',venue:'venue',address:'address',capacity:'capacity',coverUrl:'cover_url',description:'description',status:'status'};for(const [a,b]of Object.entries(pairs))if(a in p)v[b]=p[a as keyof typeof p]??null;return v;}
export async function createEvent(p:T.EventInput){await admin();return event(await write('events',eventValue(p)));}
export async function updateEvent(id:string,p:Partial<T.EventInput>){await admin();return event(await write('events',eventValue(p),id));}
export async function deleteEvent(id:string){await admin();await remove('events',id);}
export async function uploadEventCover(file:File){await admin();if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new PlatformError('conflict','Use a JPG, PNG or WebP image under 5 MB');const path=crypto.randomUUID()+'.'+({ 'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type]);const {error}=await db().storage.from('platform-covers').upload(path,file,{contentType:file.type,upsert:false});fail(error);return db().storage.from('platform-covers').getPublicUrl(path).data.publicUrl;}
export async function adminListRsvps(eventId:string){await admin();const rs=(await rows('event_rsvps')).filter(r=>r.event_id===eventId);const members=await rows('profiles');return rs.map(r=>{const m=members.find(m=>m.id===r.user_id);return rsvpMap({...r,member_name:m?.name,member_email:m?.email});});}
export async function setRsvpStatus(id:string,status:T.RsvpStatus){await admin();return rsvpMap(await rpc('admin_rsvp',{p_rsvp_id:id,p_status:status,p_check_in:null}));}
export async function checkIn(id:string,on:boolean){await admin();return rsvpMap(await rpc('admin_rsvp',{p_rsvp_id:id,p_status:null,p_check_in:on}));}
export async function adminListDeals(){await admin();return (await rows('deals')).map(deal);}
function dealValue(p:Partial<T.DealInput>){const v:Record<string,unknown>={};const pairs={slug:'slug',name:'name',line:'line',sector:'sector',city:'city',about:'about',minCheck:'min_check',valuationCap:'valuation_cap',instrument:'instrument',goal:'goal',status:'status',isSample:'is_sample',coverUrl:'cover_url',traction:'traction',useOfFunds:'use_of_funds'};for(const [a,b] of Object.entries(pairs))if(a in p)v[b]=p[a as keyof typeof p]??null;return v;}
export async function createDeal(p:T.DealInput){await admin();return deal(await write('deals',dealValue(p)));}
export async function updateDeal(id:string,p:Partial<T.DealInput>){await admin();return deal(await write('deals',dealValue(p),id));}
export async function deleteDeal(id:string){await admin();await remove('deals',id);}
export async function adminListQuestions(opts:{open?:boolean}={}){await admin();const qs=await rows('deal_questions');const members=await rows('profiles');return qs.filter(q=>!opts.open||(!q.answer&&!q.hidden)).map(q=>question({...q,member_name:members.find(m=>m.id===q.user_id)?.name}));}
export async function answerQuestion(id:string,answer:string){await admin();return question(await rpc('moderate_question',{p_question_id:id,p_answer:answer,p_hidden:null}));}
export async function setQuestionHidden(id:string,hidden:boolean){await admin();return question(await rpc('moderate_question',{p_question_id:id,p_answer:null,p_hidden:hidden}));}
export async function adminListMembers(opts:{q?:string}={}){await admin();const q=opts.q?.toLowerCase();return (await rows('profiles')).map(member).filter(m=>!q||(m.name+' '+m.email).toLowerCase().includes(q));}
export async function adminGetMember(id:string){await admin();const m=member(await one('profiles',id));const rs=(await rows('event_rsvps')).filter(r=>r.user_id===id);const rsvps=await Promise.all(rs.map(async r=>({...rsvpMap({...r,member_name:m.name,member_email:m.email}),event:await getEvent(r.event_id)})));return {...m,rsvpCount:rs.length,rsvps};}
export async function setMemberRole(id:string,role:'member'|'admin'){await admin();await rpc('set_role',{p_user_id:id,p_role:role==='member'?'user':role});return member(await one('profiles',id));}
export async function listAnnouncements():Promise<T.Announcement[]>{await admin();return (await rows('announcements')).map(r=>({id:r.id,title:r.title,body:r.body,audience:r.audience,sentAt:r.sent_at,createdBy:r.created_by,createdAt:r.created_at}));}
export async function sendAnnouncement(p:{title:string;body:string;audience:T.Audience}):Promise<T.Announcement>{await admin();const r=await rpc('announce',{p_title:p.title,p_body:p.body,p_audience:p.audience});return {id:r.id,title:r.title,body:r.body,audience:r.audience,sentAt:r.sent_at,createdBy:r.created_by,createdAt:r.created_at};}
export async function adminListWaitlist(opts:{q?:string;limit?:number;offset?:number}={}){await admin();const data=await rpc('waitlist',{p_query:opts.q||'',p_limit:opts.limit||50,p_offset:opts.offset||0});return {rows:(data.rows||[]).map((r:any)=>({id:r.id,email:r.email,name:r.name,source:r.source,createdAt:r.created_at})) as T.WaitlistEntry[],total:Number(data.total||0)};}
export async function getSettings():Promise<T.Settings>{const r=await one('settings','true');return {orgName:r.org_name,contactEmail:r.contact_email,defaultCapacity:r.default_capacity,requireApproval:r.require_approval};}
export async function updateSettings(p:Partial<T.Settings>){await admin();const v:Record<string,unknown>={};if(p.orgName!==undefined)v.org_name=p.orgName;if(p.contactEmail!==undefined)v.contact_email=p.contactEmail;if(p.defaultCapacity!==undefined)v.default_capacity=p.defaultCapacity;if(p.requireApproval!==undefined)v.require_approval=p.requireApproval;await write('settings',v,'true');return getSettings();}
export async function adminStats():Promise<T.AdminStats>{await admin();const [ms,es,rs,ds,qs,wl]=await Promise.all([rows('profiles'),rows('events'),rows('event_rsvps'),rows('deals'),rows('deal_questions'),adminListWaitlist({limit:1})]);return {members:ms.length,admins:ms.filter(m=>m.role==='admin').length,eventsUpcoming:es.filter(e=>e.status==='published'&&e.starts_at>=new Date().toISOString()).length,rsvpsPending:rs.filter(r=>r.status==='pending').length,dealsPreview:ds.filter(d=>d.status==='preview').length,questionsOpen:qs.filter(q=>!q.answer&&!q.hidden).length,waitlist:wl.total};}
